name: summerschool25
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.11
  # For xcengine
  - click
  - docker-py
  - ipython
  - nbconvert
  - nbformat
  - pystac
  - pyyaml >=5.1
  - xarray
  - xcube >=1.8.3
  - cwltool
  # For the example notebook
  - matplotlib-base
  # We use Jupyter Lab as the main learning environment for the course.
  - jupyterlab
  # xcengine itself, and pip to install it. There's a conda-forge package for
  # xcengine, but here we want the very latest version straight from GitHub.
  - pip
  - pip:
    - git+https://github.com/xcube-dev/xcengine.git@main
